- name: Create Directories with Ownership, Group and Permissions Settings
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    recurse: "{{ item.recurse | default(omit) }}"
    state: directory
  loop: "{{ directory }}" 
  tags: directories